modules:
  filesystem:
    show_smart: true
    fs_paths:
      - {path: /,           name: root}
      - {path: /boot,       name: boot}
      - {path: /home,       name: home}
      - {path: /mnt/data,   name: data}
      - {path: /mnt/dcache, name: dcache}
      - {path: /tmp,        name: tmpfs}
  graphics:
    show_temp: true
    show_clock: true
    show_gpu_util: true
    show_mem_util: true
    show_vid_util: true
  memory:
    show_stats: true
    show_plot: true
    show_table: true
  power:
    battery: BAT0
    rapl_specs:
      - {name: PKG0, address: intel-rapl:0}
      - {name: DRAM, address: intel-rapl:0:2}
  processor:
    show_cores: true
    show_stats: true
    show_plot: true
    show_table: true
  readwrite:
    devices: [sda, nvme0n1]
layout:
  anchor: [12, 11]
  panels:
    - columns:
        - {blocks: [system, 19, graphics, 16, processor], width: 436}
      margins: [20, 10]
    - 10
    - columns:
        - {blocks: [readwrite], width: 436}
        - 20
        - {blocks: [network], width: 436}
      margins: [20, 10]
    - 10
    - columns:
        - {blocks: [pacman, 24, filesystem, 24, power, 19, memory], width: 436}
      margins: [20, 10]
