local M = {}

M.LEFT_X = 32
M.SECTION_WIDTH	= 436
M.CENTER_PAD = 20
M.PANEL_HORZ_SPACING = 10
M.PANEL_MARGIN_X = 20
M.PANEL_MARGIN_Y = 10
M.TOP_Y	= 21
M.SIDE_HEIGHT = 1020
M.CENTER_HEIGHT = 220

local margin_width = M.PANEL_MARGIN_X * 2 + M.PANEL_HORZ_SPACING

M.CENTER_LEFT_X = M.LEFT_X + M.SECTION_WIDTH + margin_width
M.CENTER_RIGHT_X = M.CENTER_LEFT_X + M.SECTION_WIDTH + M.CENTER_PAD
M.CENTER_WIDTH = M.SECTION_WIDTH * 2 + M.CENTER_PAD
M.RIGHT_X = M.CENTER_LEFT_X + M.CENTER_WIDTH + margin_width

return M
